/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/media/$slug',
  path: '/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media': typeof MediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/media/$slug' | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media/$slug' | '/media'
  id: '__root__' | '/' | '/media/$slug' | '/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaSlugRoute: typeof MediaSlugRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/media/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaSlugRoute: MediaSlugRoute,
  MediaIndexRoute: MediaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
